version: '3.8'

services:
  db:
    image: postgres:15
    container_name: devops_sample_db
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops_sample_web
    command: >
      sh -c "python manage.py migrate &&
             uwsgi --http :8000 --module parrotsite.wsgi:application --master --processes 4 --threads 2"
    environment:
      DATABASE_URL: postgres://django:django@db:5432/django_db
      DJANGO_DEBUG: "False"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
